#!/usr/bin/env python3


import asyncio
import random
from typing import Generator, List


async def async_generator() -> Generator[float, None, None]:
    """Asynchronous generator that yields random numbers between 0 and 10."""
    for _ in range(10):
        await asyncio.sleep(1)
        yield random.uniform(0, 10)


async def async_comprehension() -> List[float]:
    """
    Asynchronously collects 10 random numbers generated by async_generator.
    """
    return [i async for i in async_generator()]


async def print_yielded_values():
    result = await async_comprehension()
    print(result)

# Running the asyncio event loop
if __name__ == "__main__":
    asyncio.run(print_yielded_values())
