#!/usr/bin/env python3
import asyncio

# Import async_generator from 0-async_generator module
async_generator = __import__('0-async_generator').async_generator


async def print_yielded_values():
    """Collects and prints all values generated by async_generator."""
    result = []
    async for i in async_generator():
        result.append(i)
    print(result)

# Manual event loop setup for Python 3.6
if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(print_yielded_values())
    finally:
        loop.close()
